name: Deploy

on:
  workflow_run:
    workflows: ["test"]
    types: [completed]

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          # Deploy
          - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
            with:
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_app_name: "deploy-css" #Must be unique in Heroku
              heroku_email: "chiziwe@yandex.ru"
